// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pandemic_MIS.Services.PandemicVaccineManagementAPI.Data;

#nullable disable

namespace Pandemic_MIS.Services.PandemicVaccineManagementAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240211132905_AddFieldsToVaccinationsTable")]
    partial class AddFieldsToVaccinationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pandemic_MIS.Services.PandemicVaccineManagementAPI.Models.PandemicVaccination", b =>
                {
                    b.Property<int>("PandemicVaccinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PandemicVaccinationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfVaccination")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GramaNiladhariArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOHArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NICNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NextAppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<int>("VaccinationCentreId")
                        .HasColumnType("int");

                    b.Property<string>("VaccineDose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PandemicVaccinationId");

                    b.ToTable("PandemicVaccinations");

                    b.HasData(
                        new
                        {
                            PandemicVaccinationId = 1,
                            Address = "538/7 Aluthmawatha Road, Piliyandala",
                            Age = 32,
                            CreatedBy = "rgpeiris-927810379V",
                            CreatedDate = new DateTime(2024, 2, 11, 18, 59, 4, 907, DateTimeKind.Local).AddTicks(3925),
                            DateOfVaccination = new DateTime(2024, 2, 11, 18, 59, 4, 907, DateTimeKind.Local).AddTicks(3908),
                            District = "Colombo",
                            Gender = "Female",
                            GramaNiladhariArea = "Grama Niladhari Area Piliyandala",
                            MOHArea = "MOH Office Piliyandala",
                            NICNumber = "917283783V",
                            Name = "Janvi Fernando",
                            NextAppointmentDate = new DateTime(2024, 5, 11, 18, 59, 4, 907, DateTimeKind.Local).AddTicks(3909),
                            PhoneNumber = "772523191",
                            SerialNumber = 1,
                            VaccinationCentreId = 1,
                            VaccineDose = "1st Dose",
                            VaccineName = "Sinopharm"
                        });
                });

            modelBuilder.Entity("Pandemic_MIS.Services.PandemicVaccineManagementAPI.Models.PandemicVaccine", b =>
                {
                    b.Property<int>("VaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NextDose")
                        .HasColumnType("int");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaccineId");

                    b.ToTable("PandemicVaccines");

                    b.HasData(
                        new
                        {
                            VaccineId = 1,
                            CreatedBy = "hp_anushka",
                            CreatedDate = new DateTime(2024, 2, 11, 18, 59, 4, 907, DateTimeKind.Local).AddTicks(3745),
                            Dose = "1st Dose",
                            NextDose = 3,
                            VaccineName = "Sinopharm"
                        },
                        new
                        {
                            VaccineId = 2,
                            CreatedBy = "hp_anushka",
                            CreatedDate = new DateTime(2024, 2, 11, 18, 59, 4, 907, DateTimeKind.Local).AddTicks(3799),
                            Dose = "1st Dose",
                            NextDose = 3,
                            VaccineName = "Pfizer"
                        });
                });

            modelBuilder.Entity("Pandemic_MIS.Services.PandemicVaccineManagementAPI.Models.ScheduledVaccinationCentre", b =>
                {
                    b.Property<int>("ScheduledVaccinationCentreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduledVaccinationCentreId"));

                    b.Property<int>("AvailableCapacity")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateScheduled")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeScheduled")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VaccinationCentreId")
                        .HasColumnType("int");

                    b.HasKey("ScheduledVaccinationCentreId");

                    b.ToTable("ScheduledVaccinationCentres");

                    b.HasData(
                        new
                        {
                            ScheduledVaccinationCentreId = 1,
                            AvailableCapacity = 500,
                            CreatedBy = "hp_anushka",
                            CreatedDate = new DateTime(2024, 2, 11, 18, 59, 4, 907, DateTimeKind.Local).AddTicks(3857),
                            DateScheduled = new DateTime(2024, 2, 11, 18, 59, 4, 907, DateTimeKind.Local).AddTicks(3854),
                            TimeScheduled = "Forenoon",
                            VaccinationCentreId = 1
                        });
                });

            modelBuilder.Entity("Pandemic_MIS.Services.PandemicVaccineManagementAPI.Models.VaccinationCentre", b =>
                {
                    b.Property<int>("VaccinationCentreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccinationCentreId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaccinationCentreId");

                    b.ToTable("VaccinationCentres");

                    b.HasData(
                        new
                        {
                            VaccinationCentreId = 1,
                            Address = "RW99+J9X, Makuluduwa Rd, Piliyandala",
                            CentreName = "MOH Office Piliyandala",
                            City = "Piliyandala",
                            CreatedBy = "hp_anushka",
                            CreatedDate = new DateTime(2024, 2, 11, 18, 59, 4, 907, DateTimeKind.Local).AddTicks(3828),
                            District = "Colombo",
                            IsActive = true,
                            Latitude = 6.8018029999999996,
                            Longitude = 79.922684000000004,
                            PhoneNumber = "0112 708 553"
                        });
                });

            modelBuilder.Entity("Pandemic_MIS.Services.PandemicVaccineManagementAPI.Models.VaccineAppointment", b =>
                {
                    b.Property<int>("VaccineAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineAppointmentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateScheduled")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequiredReports")
                        .HasColumnType("bit");

                    b.Property<string>("NICNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeScheduled")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VaccinationCentreId")
                        .HasColumnType("int");

                    b.HasKey("VaccineAppointmentId");

                    b.ToTable("VaccineAppointments");

                    b.HasData(
                        new
                        {
                            VaccineAppointmentId = 1,
                            Address = "538/7 Aluthmawatha Road, Colombo",
                            Age = 32,
                            BirthYear = 1991,
                            CreatedBy = "rgpeiris-927810379V",
                            CreatedDate = new DateTime(2024, 2, 11, 18, 59, 4, 907, DateTimeKind.Local).AddTicks(3881),
                            DateScheduled = new DateTime(2024, 2, 11, 18, 59, 4, 907, DateTimeKind.Local).AddTicks(3879),
                            Gender = "Female",
                            IsRequiredReports = false,
                            NICNumber = "917283783V",
                            Name = "Janvi Fernando",
                            PhoneNumber = "772523191",
                            Status = "SCHEDULED",
                            TimeScheduled = "Forenoon",
                            VaccinationCentreId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
