// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pandemic_MIS.Services.PatientManagementAPI.Data;

#nullable disable

namespace Pandemic_MIS.Services.PatientManagementAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240115115050_SeedPatientMedicalHistoryTable")]
    partial class SeedPatientMedicalHistoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pandemic_MIS.Services.PatientManagementAPI.Models.HealthcareProfessional", b =>
                {
                    b.Property<int>("HealthcareProfessionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthcareProfessionalId"));

                    b.Property<int>("AssignedHospital")
                        .HasColumnType("int");

                    b.Property<string>("AssignedUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthcareProfessionalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalSpecialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HealthcareProfessionalId");

                    b.ToTable("HealthcareProfessionals");

                    b.HasData(
                        new
                        {
                            HealthcareProfessionalId = 1,
                            AssignedHospital = 1,
                            AssignedUsername = "hp_aweerasinghe",
                            HealthcareProfessionalName = "Prof. Anura Weerasinghe",
                            IsActive = true,
                            MedicalSpecialty = "Physician",
                            PhoneNumber = "(+94) 11 541 0000"
                        });
                });

            modelBuilder.Entity("Pandemic_MIS.Services.PatientManagementAPI.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalId");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            HospitalId = 1,
                            Address = "WV99+FHX, Colombo 00700",
                            City = "Colombo",
                            District = "Colombo",
                            HospitalName = "National Hospital of SriLanka",
                            IsActive = true,
                            PhoneNumber = "(+94) 11 269 1111"
                        });
                });

            modelBuilder.Entity("Pandemic_MIS.Services.PatientManagementAPI.Models.LocalGovernmentInCharge", b =>
                {
                    b.Property<int>("LocalGovernmentInChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalGovernmentInChargeId"));

                    b.Property<string>("AssignedDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocalGovernmentInChargeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalGovernmentInChargeId");

                    b.ToTable("LocalGovernmentInCharge");

                    b.HasData(
                        new
                        {
                            LocalGovernmentInChargeId = 1,
                            AssignedDistrict = "Colombo",
                            AssignedUsername = "gic_tgamage",
                            Designation = "Physician",
                            IsActive = true,
                            LocalGovernmentInChargeName = "Prof. Thisara Gamage",
                            PhoneNumber = "(+94) 11 269 1155"
                        });
                });

            modelBuilder.Entity("Pandemic_MIS.Services.PatientManagementAPI.Models.PandemicPatient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriticalMedicalInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSDivision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfHospitalization")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRecovery")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstNegativeConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ForeignEntrant")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GramaNiladhariArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianAssignedUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianNICNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianRelationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HealthcareProfessionalInCharge")
                        .HasColumnType("int");

                    b.Property<string>("HospitalAdmissionNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int>("LocalGovernmentInCharge")
                        .HasColumnType("int");

                    b.Property<string>("MOHArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalReportingAgency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NICNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherMedicalNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendedTreatmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReleaseInfoCertifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseInfoRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedHealthCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SecondNegativeConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeverityUponDiagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("PandemicPatients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Address = "Colombo",
                            Age = 32,
                            BedNumber = "",
                            ConfirmedDate = new DateTime(2024, 1, 15, 17, 20, 50, 383, DateTimeKind.Local).AddTicks(6516),
                            CreatedBy = "rgpeiris",
                            CreatedDate = new DateTime(2024, 1, 15, 17, 20, 50, 383, DateTimeKind.Local).AddTicks(6526),
                            CriticalMedicalInformation = "N/A",
                            DSDivision = "Colombo",
                            DateOfBirth = new DateTime(2024, 1, 15, 17, 20, 50, 383, DateTimeKind.Local).AddTicks(6518),
                            DateOfDeath = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfHospitalization = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfRecovery = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Colombo",
                            FirstNegativeConfirmationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ForeignEntrant = false,
                            Gender = "Male",
                            GramaNiladhariArea = "GramaNiladhariArea",
                            GuardianAddress = "Colombo",
                            GuardianAssignedUsername = "gp_gdesilva",
                            GuardianNICNumber = "757237777V",
                            GuardianName = "Gamini De Silva",
                            GuardianPhoneNumber = "(+94) 77 260 7755",
                            GuardianRelationship = "Father",
                            HealthcareProfessionalInCharge = 0,
                            HospitalAdmissionNo = "",
                            HospitalId = 0,
                            LocalGovernmentInCharge = 1,
                            MOHArea = "Colombo",
                            MedicalReportingAgency = "Medical Reporting Agency 1",
                            NICNumber = "912837882V",
                            OtherMedicalNotes = "N/A",
                            PassportNumber = "N7464213",
                            PatientName = "Ashen De Silva",
                            PhoneNumber = "(+94) 77 260 1155",
                            RecommendedTreatmentType = "",
                            RegistrationDate = new DateTime(2024, 1, 15, 17, 20, 50, 383, DateTimeKind.Local).AddTicks(6505),
                            ReleaseInfoCertifiedBy = 0,
                            ReleaseInfoRemarks = "",
                            ReportedHealthCenter = "Reported Health Center 1",
                            SecondNegativeConfirmationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeverityUponDiagnosis = "",
                            Status = "REGISTRATION COMPLETED",
                            WardNumber = ""
                        });
                });

            modelBuilder.Entity("Pandemic_MIS.Services.PatientManagementAPI.Models.PatientMedicalHistory", b =>
                {
                    b.Property<int>("PatientMedicalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientMedicalHistoryId"));

                    b.Property<string>("DiagnosisSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExaminedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExaminedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientMedicalHistoryId");

                    b.ToTable("PatientMedicalHistories");

                    b.HasData(
                        new
                        {
                            PatientMedicalHistoryId = 1,
                            DiagnosisSummary = "Diagnosis summary",
                            ExaminedBy = 1,
                            ExaminedDate = new DateTime(2024, 1, 15, 17, 20, 50, 383, DateTimeKind.Local).AddTicks(6541),
                            PatientId = 1,
                            Remarks = "Remarks",
                            Treatments = "Treatments"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
